# Generated by Django 4.2 on 2024-09-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_type', models.CharField(choices=[('appartment', 'Appartment'), ('office', 'Office'), ('construction', 'Construction materials'), ('others', 'Others')], default='appartment', max_length=20, verbose_name='Moving Type')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('tel_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel Number')),
                ('place_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place From')),
                ('place_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place To')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance in KM')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('which_date', models.DateTimeField(blank=True, null=True, verbose_name='Which Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
