# Generated by Django 4.2 on 2024-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Your Name')),
                ('subject', models.CharField(max_length=254, verbose_name='Subject')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('message', models.TextField(verbose_name='Your Message')),
            ],
            options={
                'verbose_name': 'Contact us message',
                'verbose_name_plural': 'Contact us messages',
            },
        ),
    ]
