# Generated by Django 4.2 on 2024-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='moving_type',
            field=models.CharField(choices=[('apartment', 'Appartment'), ('office', 'Office'), ('construction', 'Construction materials'), ('other', 'Others')], default='apartment', max_length=20, verbose_name='Moving Type'),
        ),
    ]
