# Generated by Django 4.2 on 2024-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_moving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason for Cancel'),
        ),
    ]
