# Generated by Django 4.2 on 2024-09-16 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_order_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sales', to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Hot Sale',
                'verbose_name_plural': 'Hot Sales',
            },
        ),
    ]
