# Generated by Django 4.2 on 2024-09-16 11:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hotsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprice',
            name='box_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='The price per box'),
        ),
    ]
