# Generated by Django 4.2 on 2024-09-16 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_supplierprice_box_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='order',
            name='boxes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Boxes number'),
        ),
    ]
