# Generated by Django 4.2 on 2024-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Rating'),
        ),
    ]
